services:

  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data:ro

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ml-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
